# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date & time')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='latitude')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='longitude')),
                ('ele', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='elevation')),
                ('pm25', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='PM2.5')),
                ('pm10', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='PM10')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
    ]
