# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='ele',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='elevation'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True, verbose_name='longitude'),
        ),
    ]
